name: Desktop File Ops

on:
  workflow_dispatch:  # lets you run it manually

jobs:
  file_tasks:
    runs-on: self-hosted

    steps:
      - name: Create folder1 and file 1.txt on Desktop
        shell: pwsh
        run: |
          $desktop = [Environment]::GetFolderPath("Desktop")
          $folder1 = Join-Path $desktop "folder1"
          New-Item -ItemType Directory -Path $folder1 -Force
          $file1 = Join-Path $folder1 "1.txt"
          Set-Content -Path $file1 -Value "Created via GitHub Actions"

      - name: Create folder2 on Desktop
        shell: pwsh
        run: |
          $desktop = [Environment]::GetFolderPath("Desktop")
          $folder2 = Join-Path $desktop "folder2"
          New-Item -ItemType Directory -Path $folder2 -Force

      - name: Copy 1.txt from folder1 to folder2
        shell: pwsh
        run: |
          $desktop = [Environment]::GetFolderPath("Desktop")
          $source = Join-Path $desktop "folder1\1.txt"
          $destination = Join-Path $desktop "folder2\1.txt"
          Copy-Item -Path $source -Destination $destination -Force
